version: "3.9"

services:
  app:
    container_name: app
    build: ./app/
    ports:
      - "3000:3000"
    volumes:
      - ./app:/project
      - ./app/tmp:/tmp
    tty: true

  web:
    container_name: web
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/tmp:/tmp
    depends_on: 
      - app

  db:
    container_name: db
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"