version: "3.9"

services:
  web:
    image: nginx:1.23.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/index.html:/tmp/index.html

  app:
    image: python:3.12.0a7-alpine3.17
    working_dir: /code
    ports:
      - "3000:3000"
    volumes:
      - ./app:/code
    tty: true

  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"